name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build: 
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.DEBIAN_CI }}
      credentials:
        username: circle4regentmarkets
        password: ${{ secrets.DOCKER_PASSWORD }}
      options: --user nobody:nogroup
    defaults:
      run:
        shell: bash -le {0}
    steps:
      - name: setup CI step
        uses: regentmarkets/github-actions/ci-setup@master
        with:
          read_github_ssh_key: ${{ secrets.READ_GITHUB_SSH_KEY }}
          need_service: false
          repository: ${{ github.repository }}
      - name : Run Tests 
        run: |
          source /etc/profile.d/perl5.sh
          dzil test && dzil xtest
        working-directory: /home/git/${{ github.repository }}
